New post 2019-12-19: Temporal Difference Learning
aarl-ieee-nitk/aarl-ieee-nitk.github.io pull request #1
Opened 2019-12-19 14:17 UTC by vrn25

2019-12-23 21:21 UTC, nimbus98 commented
Looks good to me.
Good Job!

2019-12-26 14:08 UTC, MJ10 requested changes
Great work! Article is written well. I have left a few specific comments. 
Another general comment: If you have so much code and such detailed output, it is better to have it separately in a notebook/repo.

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +While sampling methods like **Monte-Carlo** (MC) prove to be advantageous over **Dynamic Programming** (DP) algorithms, a significant problem associated with them is that we have to wait for the epis
"_The discounted sum of rewards till the end of the episode is used as the return value (**$G_t$**)._" Isn't this literally the definition? What's special in case of MC methods?

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +It turns out that we have already solved this problem in DP. Recall that DP uses **bootstrapping** for making updates. So instead of waiting till the end of the episode, we consider the true discount
"_It turns out that we have already solved this problem in DP. Recall that DP uses **bootstrapping** for making updates._" -> Dynamic Programming already provides a way to tackle this problem in the form of bootstrapping.

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +<p align="center"><img src="/css/compare_methods.png"/ alt="Value-based-methods"></p>
Why is the image in the css directory?

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +**Temporal Difference** (TD) learning is a model-free method that combines the sampling nature of Monte-Carlo with the bootstrapping behavior of DP. Model-free means that we need not know the details
"_**Temporal Difference** (TD) learning is a model-free method_" -> **Temporal Difference** (TD) learning is a family of model-free methods that combine

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +One of the major contrasting features between MC and TD learning is that TD learning is
If you're stating this also back it up with a reason.

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +The error is weighed by a step-size parameter **$\alpha$** (learning rate), which indicates the extent to which the new information about the current state ($R_{t+1} + \gamma V(S_{t+1})$) is acquired
alpha does not indicate the extent to which new information is acquired. It indicates the extent to which the new information updates our current estimate.

2019-12-26 14:08 UTC, MJ10 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +The Control problem requires us to find both the optimal policy as well as value function. Here comes the dilemma of **Exploration** and **Exploitation**. This is one of the most fundamental problems
_This is one of the most fundamental problems in RL, and people have come up with various methods to solve it._ => It is still an open problem. It's a fundamental trade-off. So a better way to put it would be "Various approaches have been proposed over the years to strike a good balance between the two."

2019-12-27 00:12 UTC, vrn25 commented on _posts/2019-12-19-Temporal-Difference-Learning.md
> +While sampling methods like **Monte-Carlo** (MC) prove to be advantageous over **Dynamic Programming** (DP) algorithms, a significant problem associated with them is that we have to wait for the epis
"end of the episode"
I think "target value" would be better to use, instead of return value.

2019-12-28 12:18 UTC, vrn25 commented
Changes requested addressed

2020-01-13 13:45 UTC, nimbus98 commented
@MJ10 Shall I merge the request?

2020-01-14 02:50 UTC, MJ10 approved these changes

2020-01-17 12:09 UTC, merged